"""Phase 1 - IEEE-CIS data audit.

Reads the raw CSVs once and writes docs/audit.md. Everything downstream (the
feature shortlist, the time split, the leakage calls) is decided from this
report, so it runs before any modelling.

    python -m ml.audit
"""
import json

import numpy as np
import pandas as pd

from config import ROOT, settings
from ml.features import load_raw

SECONDS_PER_DAY = 86400
TRAIN_FRACTION = 0.8  # chronological, not random - see "Time split" below


def column_table(df: pd.DataFrame) -> pd.DataFrame:
    """Per-column dtype, missingness, cardinality and modal share."""
    top_share = df.apply(lambda s: s.value_counts(dropna=True, normalize=True).max())
    return pd.DataFrame(
        {
            "dtype": df.dtypes.astype(str),
            "null_pct": (df.isna().mean() * 100).round(2),
            "nunique": df.nunique(dropna=True),
            "top_share": top_share.round(4),
        }
    )


def correlated_pairs(
    df: pd.DataFrame, cols: list[str], threshold: float = 0.95, sample_rows: int = 100_000
) -> list[tuple[str, str, float]]:
    """V-columns are heavily redundant. Find pairs above `threshold` so the
    feature step can drop one of each pair instead of carrying all 339.

    Estimated on a row sample: `corr()` upcasts 339 float32 columns to float64,
    which costs ~1.6GB over the full 590k rows and thrashes a 16GB machine. A
    >=0.95 redundancy screen is stable well below that.
    """
    data = df[cols]
    if len(data) > sample_rows:
        data = data.sample(sample_rows, random_state=settings.random_seed)
    corr = data.corr().abs().to_numpy()
    rows, cols_i = np.triu_indices_from(corr, k=1)
    values = corr[rows, cols_i]
    hits = np.flatnonzero(values >= threshold)
    order = hits[np.argsort(-values[hits])]
    return [(cols[rows[i]], cols[cols_i[i]], float(values[i])) for i in order]


def fraud_rate_by(df: pd.DataFrame, col: str, min_count: int = 500) -> pd.DataFrame:
    """Fraud rate per category, ignoring slices too small to mean anything."""
    grouped = df.groupby(col, dropna=False)["isFraud"].agg(["count", "mean"])
    grouped = grouped[grouped["count"] >= min_count].sort_values("mean", ascending=False)
    grouped["fraud_pct"] = (grouped["mean"] * 100).round(2)
    return grouped.drop(columns="mean")


def md_table(df: pd.DataFrame, index_name: str = "column") -> str:
    out = df.reset_index()
    out.columns = [index_name if i == 0 else str(c) for i, c in enumerate(out.columns)]
    header = "| " + " | ".join(out.columns) + " |"
    sep = "|" + "|".join(["---"] * len(out.columns)) + "|"
    rows = ["| " + " | ".join(str(v) for v in row) + " |" for row in out.itertuples(index=False)]
    return "\n".join([header, sep] + rows)


def build_report(df: pd.DataFrame) -> tuple[str, dict]:
    n = len(df)
    fraud_rate = df["isFraud"].mean()
    dt = df["TransactionDT"]
    split_dt = float(dt.quantile(TRAIN_FRACTION))
    amt = df["TransactionAmt"]
    is_fraud = df["isFraud"] == 1
    # Folklore says card-testing shows up as odd sub-unit amounts. Measured
    # below rather than assumed - on this dataset it does not hold.
    cents = (amt * 100).round().mod(100)

    stats = column_table(df)
    ident_cols = [c for c in df.columns if c.startswith("id_")]
    v_cols = [c for c in df.columns if c.startswith("V") and c[1:].isdigit()]
    cats = ["ProductCD", "card4", "card6", "P_emaildomain", "R_emaildomain", "M4", "DeviceType"]

    near_constant = stats[stats["top_share"] > 0.99].index.tolist()
    mostly_null = stats[stats["null_pct"] > 90].index.tolist()
    pairs = correlated_pairs(df, v_cols)
    dropped_v = {b for _, b, _ in pairs}

    excluded = {"TransactionID", "isFraud", "TransactionDT"}
    keep = [
        c
        for c in df.columns
        if c not in excluded
        and c not in dropped_v
        and c not in near_constant
        and stats.loc[c, "null_pct"] <= 90
    ]

    train_rate = df.loc[dt < split_dt, "isFraud"].mean() * 100
    val_rate = df.loc[dt >= split_dt, "isFraud"].mean() * 100
    id_coverage = df[ident_cols[0]].notna().mean() * 100 if ident_cols else 0.0

    lines = [
        "# IEEE-CIS Data Audit",
        "",
        "Generated by `python -m ml.audit`. Every downstream choice cites this file.",
        "",
        "## Shape and balance",
        "",
        f"- Rows: **{n:,}**, columns: **{df.shape[1]}** "
        "(394 transaction + 41 identity, joined on `TransactionID`)",
        f"- Fraud: **{int(df['isFraud'].sum()):,}** rows = **{fraud_rate * 100:.2f}%** "
        f"- imbalance ratio **1:{(1 - fraud_rate) / fraud_rate:.0f}**",
        f"- Identity join coverage: **{id_coverage:.1f}%** of transactions carry identity data",
        "",
        "PR-AUC is the headline metric. At this base rate a model that predicts "
        f"'never fraud' scores {(1 - fraud_rate) * 100:.1f}% accuracy, so accuracy is "
        "meaningless here.",
        "",
        "## Time split",
        "",
        f"- `TransactionDT` is a **seconds offset**, not a unix timestamp: "
        f"min={dt.min():,.0f} (day {dt.min() / SECONDS_PER_DAY:.1f}), "
        f"max={dt.max():,.0f} (day {dt.max() / SECONDS_PER_DAY:.1f})",
        f"- Span: **{(dt.max() - dt.min()) / SECONDS_PER_DAY:.0f} days**",
        f"- Chronological {TRAIN_FRACTION:.0%}/{1 - TRAIN_FRACTION:.0%} split at "
        f"`TransactionDT = {split_dt:,.0f}` (day {split_dt / SECONDS_PER_DAY:.1f})",
        f"- Fraud rate: train **{train_rate:.2f}%** vs validation **{val_rate:.2f}%**",
        "",
        "Split by time, never randomly. Card and address history bleeds across a random "
        "split and inflates every reported number.",
        "",
        "## Amount",
        "",
        f"- Range {amt.min():,.2f} - {amt.max():,.2f}, median {amt.median():,.2f}, "
        f"mean {amt.mean():,.2f}",
        f"- Fraud median {amt[is_fraud].median():,.2f} vs legit median "
        f"{amt[~is_fraud].median():,.2f}",
        f"- Non-zero cents: **{(cents > 0).mean() * 100:.1f}%** of all rows vs "
        f"**{(cents[is_fraud] > 0).mean() * 100:.1f}%** of fraud - **no usable signal**, "
        "so no cents flag is built. The raw amount is kept and the model can find any "
        "finer structure itself.",
        "",
        "## Missingness",
        "",
        f"- Columns >90% null (**{len(mostly_null)}**, dropped): "
        f"{', '.join(mostly_null) if mostly_null else 'none'}",
        f"- Columns >50% null: **{int((stats['null_pct'] > 50).sum())}**",
        "",
        "XGBoost handles NaN natively, so missingness is treated as signal rather than "
        "imputed away.",
        "",
        "## Redundancy",
        "",
        f"- Near-constant columns (one value in >99% of rows, **{len(near_constant)}**, "
        f"dropped): {', '.join(near_constant) if near_constant else 'none'}",
        f"- V-column pairs correlated >=0.95: **{len(pairs)}**, collapsing to "
        f"**{len(dropped_v)}** dropped columns",
        "- Strongest 15 pairs: "
        + (", ".join(f"{a}~{b} ({c:.3f})" for a, b, c in pairs[:15]) if pairs else "none"),
        "",
        "## Categorical cardinality",
        "",
        md_table(stats.loc[[c for c in cats if c in stats.index], ["nunique", "null_pct", "top_share"]]),
        "",
        "## Fraud rate by key categoricals",
        "",
    ]

    for col in ("ProductCD", "card4", "card6", "DeviceType"):
        if col in df.columns:
            lines += [f"### {col}", "", md_table(fraud_rate_by(df, col), col), ""]

    def block(prefix: str) -> str:
        kept = sum(c.startswith(prefix) for c in keep)
        total = sum(c.startswith(prefix) for c in df.columns)
        return f"`{prefix}*` {kept}/{total}"

    blocks = ", ".join(block(p) for p in ("V", "C", "D", "M", "id_", "card", "addr", "dist"))
    shortlist = "\n".join(", ".join(keep[i : i + 8]) for i in range(0, len(keep), 8))
    lines += [
        "## Feature shortlist",
        "",
        f"**{len(keep)} of {df.shape[1]} columns** survive, after removing the correlated, "
        "near-constant and >90%-null columns above.",
        "",
        f"Kept per block: {blocks}.",
        "",
        "Derived in `ml/features.py` (Phase 2), not here:",
        "",
        "- `log_amount` (the raw amount spans 0.25-31,937, heavily right-skewed)",
        "- `hour_of_day` and `day_of_week` from `TransactionDT`",
        "- email domain grouping, since the provider long tail collapses to a few buckets",
        "- frequency encoding for `card1`, `addr1`, `P_emaildomain`",
        "",
        "`TransactionID` and `TransactionDT` are **excluded as model inputs**: the ID is an "
        "arbitrary counter and the raw offset would let the model memorise the split "
        "boundary. The derived hour and weekday are kept.",
        "",
        "### Shortlist",
        "",
        "```",
        shortlist,
        "```",
        "",
    ]
    decisions = {
        "rows_audited": n,
        "split_dt": split_dt,
        "dropped_high_null": mostly_null,
        "dropped_near_constant": near_constant,
        "dropped_correlated": sorted(dropped_v),
        "keep": keep,
        # Anything non-numeric is categorical. Checking `dtype == object` breaks
        # on pandas' newer `str` dtype and silently yields an empty list, which
        # would let ProductCD and the card fields be coerced to NaN downstream.
        "categorical": [c for c in keep if not pd.api.types.is_numeric_dtype(df[c])],
    }
    return "\n".join(lines), decisions


def main() -> None:
    print("Loading IEEE-CIS...", flush=True)
    df = load_raw()
    print(
        f"Loaded {len(df):,} rows x {df.shape[1]} cols, "
        f"{df.memory_usage(deep=True).sum() / 1e9:.2f} GB",
        flush=True,
    )
    report, decisions = build_report(df)

    out = ROOT / "docs" / "audit.md"
    out.parent.mkdir(exist_ok=True)
    out.write_text(report, encoding="utf-8")
    print(f"Wrote {out}")

    # Machine-readable twin of the report: ml/features.py reads this so the
    # column decisions are made once, here, and never re-derived.
    columns_out = ROOT / "ml" / "feature_columns.json"
    columns_out.write_text(json.dumps(decisions, indent=2), encoding="utf-8")
    print(f"Wrote {columns_out} ({len(decisions['keep'])} columns kept)")


if __name__ == "__main__":
    main()
