"""Phase 3 - train the fraud model and report honestly on it.

Training and evaluation live together so the 1.8GB load happens once. The run
produces three artifacts:

    models/fraud_xgb.json     the booster
    models/feature_spec.json  the fitted feature spec - a model without it cannot be served
    docs/metrics.md           ML metrics and rupee impact

    python -m ml.train
"""
import gc

import numpy as np
import pandas as pd
import xgboost as xgb
from sklearn.metrics import (
    average_precision_score,
    confusion_matrix,
    precision_recall_fscore_support,
    roc_auc_score,
)

from config import ROOT, settings
from ml.features import fit, load_raw, read_column_decisions, split, transform

MODEL_DIR = ROOT / "models"
SPEC_PATH = MODEL_DIR / "feature_spec.json"

PARAMS = {
    "n_estimators": 2000,
    "learning_rate": 0.05,
    "max_depth": 8,
    "subsample": 0.8,
    "colsample_bytree": 0.8,
    "min_child_weight": 4,
    "tree_method": "hist",  # keeps the 268-column matrix training in minutes
    "eval_metric": "aucpr",  # PR-AUC, not accuracy - the classes are 1:28
    "early_stopping_rounds": 100,
    "n_jobs": -1,
}


def money(mask: np.ndarray, amounts: pd.Series) -> float:
    return float(amounts.to_numpy()[mask].sum())


def evaluate(
    y: np.ndarray, scores: np.ndarray, amounts: pd.Series, threshold: float
) -> dict:
    """Metrics at one advisory threshold, in both counts and rupees."""
    pred = scores >= threshold
    precision, recall, f1, _ = precision_recall_fscore_support(
        y, pred, average="binary", zero_division=0
    )
    tn, fp, fn, tp = confusion_matrix(y, pred, labels=[0, 1]).ravel()
    is_fraud = y == 1
    return {
        "threshold": threshold,
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "tn": int(tn),
        "fp": int(fp),
        "fn": int(fn),
        "tp": int(tp),
        "false_positive_rate": fp / (fp + tn) if fp + tn else 0.0,
        "false_negative_rate": fn / (fn + tp) if fn + tp else 0.0,
        # The numbers a merchant actually feels.
        "legit_value_flagged": money(pred & ~is_fraud, amounts),
        "fraud_value_missed": money(~pred & is_fraud, amounts),
        "fraud_value_caught": money(pred & is_fraud, amounts),
    }


def report(
    model, spec, val_y, val_scores, val_amounts, n_train, n_val, best_iter
) -> str:
    pr_auc = average_precision_score(val_y, val_scores)
    roc_auc = roc_auc_score(val_y, val_scores)
    base_rate = val_y.mean()
    total_fraud_value = money(val_y == 1, val_amounts)

    review = evaluate(val_y, val_scores, val_amounts, settings.risk_review_threshold)
    block = evaluate(val_y, val_scores, val_amounts, settings.risk_block_threshold)

    importance = model.get_booster().get_score(importance_type="gain")
    top = sorted(importance.items(), key=lambda kv: -kv[1])[:20]

    def band(m: dict) -> list[str]:
        return [
            f"| Precision | {m['precision']:.4f} |",
            f"| Recall | {m['recall']:.4f} |",
            f"| F1 | {m['f1']:.4f} |",
            f"| True positives | {m['tp']:,} |",
            f"| False positives | {m['fp']:,} |",
            f"| False negatives | {m['fn']:,} |",
            f"| True negatives | {m['tn']:,} |",
            f"| False-positive rate | {m['false_positive_rate'] * 100:.2f}% |",
            f"| False-negative rate | {m['false_negative_rate'] * 100:.2f}% |",
            f"| Legit value flagged | {m['legit_value_flagged']:,.0f} |",
            f"| Fraud value caught | {m['fraud_value_caught']:,.0f} |",
            f"| Fraud value missed | {m['fraud_value_missed']:,.0f} |",
        ]

    lines = [
        "# Model Evaluation",
        "",
        f"Generated by `python -m ml.train`. Model version `{settings.model_version}`, "
        f"seed {settings.random_seed}.",
        "",
        "## Setup",
        "",
        f"- Train rows: **{n_train:,}** (before `TransactionDT = {spec.split_dt:,.0f}`)",
        f"- Validation rows: **{n_val:,}** (after it)",
        f"- Features: **{len(spec.columns)}**",
        f"- Best iteration: **{best_iter}** of {PARAMS['n_estimators']} "
        "(early stopping on validation PR-AUC)",
        "",
        "The split is chronological. A random split lets card and address history bleed "
        "across the boundary and inflates every number below.",
        "",
        "## Ranking quality",
        "",
        "| Metric | Value |",
        "|---|---|",
        f"| **PR-AUC** | **{pr_auc:.4f}** |",
        f"| ROC-AUC | {roc_auc:.4f} |",
        f"| Baseline PR-AUC (random) | {base_rate:.4f} |",
        f"| Lift over baseline | {pr_auc / base_rate:.1f}x |",
        "",
        "PR-AUC leads because the validation set is "
        f"{base_rate * 100:.2f}% fraud: predicting 'never fraud' scores "
        f"{(1 - base_rate) * 100:.1f}% accuracy while catching nothing, so accuracy is "
        "not reported.",
        "",
        f"## At the REVIEW threshold ({settings.risk_review_threshold})",
        "",
        "| Metric | Value |",
        "|---|---|",
        *band(review),
        "",
        f"## At the BLOCK threshold ({settings.risk_block_threshold})",
        "",
        "| Metric | Value |",
        "|---|---|",
        *band(block),
        "",
        "## Financial exposure",
        "",
        f"- Total fraud value in the validation window: **{total_fraud_value:,.0f}**",
        f"- Caught at REVIEW: **{review['fraud_value_caught']:,.0f}** "
        f"({review['fraud_value_caught'] / total_fraud_value * 100:.1f}%)",
        f"- Missed at REVIEW: **{review['fraud_value_missed']:,.0f}**",
        f"- Legitimate value sent for review: **{review['legit_value_flagged']:,.0f}** "
        f"across {review['fp']:,} transactions",
        "",
        "Every false positive is a real customer inconvenienced, so the legitimate value "
        "flagged is a cost, not a rounding error. Thresholds are policy and live in "
        "`.env`; moving them trades these two columns against each other without "
        "retraining.",
        "",
        "## Top 20 features by gain",
        "",
        "| Feature | Gain |",
        "|---|---|",
        *[f"| {name} | {gain:,.0f} |" for name, gain in top],
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    decisions = read_column_decisions()
    split_dt = float(decisions["split_dt"])

    print("Loading IEEE-CIS...", flush=True)
    df = load_raw()
    train_df, val_df = split(df, split_dt)
    n_train, n_val = len(train_df), len(val_df)
    print(f"Train {n_train:,} | Validation {n_val:,}", flush=True)

    # Fitted on training rows only. Fitting on everything would leak future card
    # frequencies backwards into the training features.
    print("Fitting feature spec on training rows...", flush=True)
    spec = fit(train_df)
    X_train, X_val = transform(train_df, spec), transform(val_df, spec)
    y_train, y_val = train_df["isFraud"].to_numpy(), val_df["isFraud"].to_numpy()
    val_amounts = val_df["TransactionAmt"].copy()
    print(f"Feature matrix: {X_train.shape[1]} columns", flush=True)

    # The raw frame is 1.8GB and nothing below needs it. Holding it through
    # training pushes a 16GB machine into swap.
    del df, train_df, val_df
    gc.collect()

    # 1:28 imbalance - without this the model optimises for the majority class.
    pos_weight = (y_train == 0).sum() / (y_train == 1).sum()
    model = xgb.XGBClassifier(
        **PARAMS, scale_pos_weight=pos_weight, random_state=settings.random_seed
    )

    print("Training...", flush=True)
    model.fit(X_train, y_train, eval_set=[(X_val, y_val)], verbose=100)

    scores = model.predict_proba(X_val)[:, 1]

    MODEL_DIR.mkdir(exist_ok=True)
    model_path = MODEL_DIR / settings.model_path.name
    model.save_model(model_path)
    spec.save(SPEC_PATH)

    metrics_path = ROOT / "docs" / "metrics.md"
    metrics_path.parent.mkdir(exist_ok=True)
    metrics_path.write_text(
        report(
            model,
            spec,
            y_val,
            scores,
            val_amounts,
            n_train,
            n_val,
            model.best_iteration,
        ),
        encoding="utf-8",
    )

    print(
        f"\nPR-AUC {average_precision_score(y_val, scores):.4f} | "
        f"ROC-AUC {roc_auc_score(y_val, scores):.4f}"
    )
    for path in (model_path, SPEC_PATH, metrics_path):
        print(f"Wrote {path}")


if __name__ == "__main__":
    main()
